# coding: utf-8

"""
    GNBR Reasoner API

    GNBR Reasoner API  # noqa: E501

    OpenAPI spec version: 0.8.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.response_api import ResponseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseApi(unittest.TestCase):
    """ResponseApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.response_api.ResponseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_response(self):
        """Test case for get_response

        Nonfunctional Endpoint  # noqa: E501
        """
        pass

    def test_get_response_feedback(self):
        """Test case for get_response_feedback

        Nonfunctional Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
