# coding: utf-8

"""
    GNBR Reasoner API

    GNBR Reasoner API  # noqa: E501

    OpenAPI spec version: 0.8.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_terms import QueryTerms  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryTerms(unittest.TestCase):
    """QueryTerms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryTerms(self):
        """Test QueryTerms"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_terms.QueryTerms()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
