# coding: utf-8

"""
    GNBR Reasoner API

    GNBR Reasoner API  # noqa: E501

    OpenAPI spec version: 0.8.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EdgeAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'value': 'str',
        'url': 'str'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'value': 'value',
        'url': 'url'
    }

    def __init__(self, type=None, name=None, value=None, url=None):  # noqa: E501
        """EdgeAttribute - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._name = None
        self._value = None
        self._url = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if value is not None:
            self.value = value
        if url is not None:
            self.url = url

    @property
    def type(self):
        """Gets the type of this EdgeAttribute.  # noqa: E501

        Entity type of this attribute  # noqa: E501

        :return: The type of this EdgeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EdgeAttribute.

        Entity type of this attribute  # noqa: E501

        :param type: The type of this EdgeAttribute.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this EdgeAttribute.  # noqa: E501

        Formal name of the attribute  # noqa: E501

        :return: The name of this EdgeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EdgeAttribute.

        Formal name of the attribute  # noqa: E501

        :param name: The name of this EdgeAttribute.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this EdgeAttribute.  # noqa: E501

        Value of the attribute. While all attributes should have a name, many will not have a value  # noqa: E501

        :return: The value of this EdgeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this EdgeAttribute.

        Value of the attribute. While all attributes should have a name, many will not have a value  # noqa: E501

        :param value: The value of this EdgeAttribute.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def url(self):
        """Gets the url of this EdgeAttribute.  # noqa: E501

        A URL corresponding to this attribute  # noqa: E501

        :return: The url of this EdgeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EdgeAttribute.

        A URL corresponding to this attribute  # noqa: E501

        :param url: The url of this EdgeAttribute.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdgeAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
